project:
  type: website
  output-dir: docs
  resources: 
    - assets/json/*
  preview:
    port: 4200
    browser: true
    watch-inputs: true

execute:
  freeze: auto

filters:
  - auto-dark
  - code-visibility

format:
  html:
    theme:
      light: [cosmo, assets/css/theme-quarto.scss]      
    css: 
      - assets/css/styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    html-math-method: katex
    number-sections: false
    code-fold: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

website:
  title: "Cours EDO"
  image: assets/images/trajectory.png
  favicon: assets/images/trajectory.svg
  open-graph: true
  twitter-card: true
  #site-url: https://ocots.github.io/course-tse-julia/
  #repo-url: https://github.com/ocots/course-tse-julia
  #issue-url: https://github.com/ocots/course-tse-julia/issues/new/choose
  #repo-actions: [edit, source, issue]
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  search: 
    location: navbar
    show-item-context: true
    type: overlay
    keyboard-shortcut: ["?", "H"]
  page-footer: 
    center: "Copyright 2025, Olivier Cots"
  navbar:
    background: light
    logo: assets/images/trajectory.svg
    logo-alt: "Julia course."
    title: false
    tools:
      - icon: github
        href: https://github.com/ocots
    left:
      - text: "Cours"
        href: src/index.qmd
  sidebar:
    - id: src
      style: "floating"
      collapse-level: 2
      contents:
        - section: "Cours"
          href: src/index.qmd
          contents:
            - section: "Introduction"
              contents: 
                - text: "Équations différentielles ordinaires"
                  href: src/introduction/edo.qmd
                - text: "Modèle de Kaplan"
                  href: src/introduction/kaplan.qmd
                - text: "Problème aux moindres carrés"
                  href: src/introduction/moindres_carres.qmd
            - section: "Équations différentielles ordinaires linéaires"
              contents: 
                - text: "Définitions"
                  href: src/edo_lineaires/definitions.qmd
                - text: "Exponentielle de matrice"
                  href: src/edo_lineaires/exponentielle.qmd
                - text: "Solution générale"
                  href: src/edo_lineaires/solution.qmd
                - text: "Exemples"
                  href: src/edo_lineaires/exemples.qmd
            - section: "Intégration numérique"
              contents: 
                - text: "Méthode d'Euler"
                  href: src/integration_numerique/euler.qmd
                - text: "Méthode de Runge-Kutta"
                  href: src/integration_numerique/runge_kutta.qmd
            - section: "Dérivées"
              contents: 
                - text: "Fonctions dérivées"
                  href: src/derivees/fonctions.qmd
                - text: "Equations variationnelles"
                  href: src/derivees/equations.qmd