---
title: "Solution du Problème de Cauchy Linéaire"
page-layout: article
---

## Cas Homogène

Considérons le problème de Cauchy linéaire homogène suivant :

$$
    x'(t) = A\, x(t), \quad x(0) = x_0
$$

où $A \in M_n(\mathbb{R})$ est une matrice constante et $x_0 \in \mathbb{R}^n$ est le vecteur d'état initial.

::: {.callout-important icon=false}
## Théorème

La solution du problème de Cauchy linéaire homogène est donnée par :

$$
    x(t, x_0) = e^{tA} x_0
$$
:::

::: {.callout-caution collapse="true" icon=false}
### Preuve

**Existence.** Montrons que $x(t, x_0) = e^{tA} x_0$ vérifie les propriétés d'une solution pour le problème de Cauchy.

- **Vérification de la Condition Initiale.**
    À $t = 0$, nous avons :
    $$
        x(0, x_0) = e^{0 \cdot A} x_0 = I x_0 = x_0
    $$
    Donc, la condition initiale est satisfaite.

- **Vérification de l'Équation Différentielle.**
    Calculons la dérivée de $x(t, x_0)$ par rapport à $t$ :
    $$
        \frac{d}{dt} x(t, x_0) = \frac{d}{dt} (e^{tA} x_0) = A e^{tA} x_0 = A x(t, x_0)
    $$
    Donc, $x(t, x_0)$ satisfait l'équation différentielle $x'(t) = A x(t)$.

Ainsi, $x(t, x_0) = e^{tA} x_0$ est bien une solution du problème de Cauchy, ce qui prouve l'existence.

**Unicité.** Supposons qu'il existe une autre solution $y(t)$ du problème de Cauchy. Définissons $z(t) = y(t) - x(t, x_0)$. Alors,

$$
    z'(t) = y'(t) - x'(t, x_0) = A y(t) - A x(t, x_0) = A (y(t) - x(t, x_0)) = A z(t)
$$

Avec la condition initiale $z(0) = y(0) - x(0, x_0) = 0$.

Considérons maintenant le changement de variable $w(t) = e^{-tA} z(t)$. Alors,

$$
    w'(t) = \frac{d}{dt} (e^{-tA} z(t)) = -A e^{-tA} z(t) + e^{-tA} z'(t) = -A w(t) + e^{-tA} A z(t) = 0
$$

Puisque $w'(t) = 0$, $w(t)$ est constante (d'après le TAF). Donc, $w(t) = w(0) = e^{-0 \cdot A} z(0) = 0$.

Ainsi, $z(t) = e^{tA} w(t) = 0$ pour tout $t$, ce qui implique que $y(t) = x(t, x_0)$. Cela prouve l'unicité de la solution.
:::

## Cas Non Homogène

Considérons maintenant le problème de Cauchy linéaire non homogène :

$$
    x'(t) = A x(t) + b(t), \quad x(t_0) = x_0,
$$

où $A \in M_n(\mathbb{R})$ est une matrice constante et $t \mapsto b(t) \in \mathbb{R}^n$ est définie et continue sur un intervalle ouvert $\mathcal{I}$ contenant $t_0$.

::: {.callout-note}
Nous supposons acquis l'existence d'une unique solution globale. 
:::

::: {.callout-important icon=false}
## Théorème

La solution du problème de Cauchy linéaire non homogène est donnée par :
$$
x(t) = e^{(t-t_0)A}\, x_0 + \int_{t_0}^{t} e^{(t-s)A}\, b(s) \, ds
$$
:::

::: {.callout-caution collapse="true" icon=false}
### Preuve

Puisque nous supposons l'existence d'une unique solution globale, il suffit de vérifier que la fonction $x(t)$ définie dans le théorème satisfait à la fois la condition initiale et l'équation différentielle. Cette vérification est laissée au lecteur. Pour retrouver son expression en s'appuyant sur la solution du cas homogène, on utilise la méthode de variation des constantes.  

**Méthode de variation des constantes.**
Posons $x(t) = e^{(t-t_0)A} z(t)$ et déterminons $z(t)$. Tout d'abord, $x(\cdot)$ doit vérifier la condition initiale :  
$$
x(t_0) = e^{(t_0-t_0)A} z(t_0) = z(t_0) = x_0,
$$  
d'où $z(t_0) = x_0$.  

Ensuite, $x(\cdot)$ doit satisfaire l'équation différentielle. En dérivant, on obtient :  
$$
x'(t) = A\, x(t) + e^{(t-t_0)A} z'(t).
$$  
Il faut donc choisir $z(\cdot)$ de manière à ce que $b(t) = e^{(t-t_0)A} z'(t)$, ce qui équivaut à $z'(t) = e^{(t_0-t)A} b(t)$.  

Enfin, en intégrant :  
$$
z(t) = x_0 + \int_{t_0}^t e^{(t_0-s)A}\, b(s)\, \mathrm{d}s.
$$  

D'où l'expression finale :  
$$
x(t) = e^{(t-t_0)A} z(t) = e^{(t-t_0)A} x_0 + \int_{t_0}^t e^{(t-s)A}\, b(s)\, \mathrm{d}s,
$$  
grâce à la propriété $e^{(t-t_0)A} e^{(t_0-s)A} = e^{(t-s)A}$.
:::

## Cas Particulier : $b$ Constant

Si $b$ est un vecteur constant (ne dépend pas du temps), nous pouvons nous ramener au cas linéaire homogène par un changement de variable. On fixe pour la suite $t_0 = 0$.

Posons $z(t) = x(t) - x_p(t)$, où $x_p(t)$ est une solution particulière de l'équation $x'(t) = A x(t) + b$. En substituant $x(t) = z(t) + x_p(t)$ dans l'équation originale, nous obtenons :
$$
    z'(t) + x'_p(t) = A(z(t) + x_p(t)) + b.
$$

Puisque $x_p(t)$ est une solution particulière, $x'_p(t) = A x_p(t) + b$. Donc,
$$
    z'(t) = A z(t).
$$

Ainsi, $z(t)$ satisfait une équation différentielle linéaire homogène. La solution de $z'(t) = A z(t)$ avec la condition initiale $z(0) = x_0 - x_p(0)$ est donnée par :
$$
    z(t) = e^{tA} (x_0 - x_p(0)).
$$

En revenant à la variable originale, nous avons :
$$
    x(t) = z(t) + x_p(t) = e^{tA} (x_0 - x_p(0)) + x_p(t).
$$

Ce changement de variable permet de ramener le problème linéaire non homogène à un problème linéaire homogène, facilitant ainsi sa résolution.

::: {.callout-note}
Si $b$ appartient à l'image de $A$, c'est-à-dire s'il existe un vecteur $x_e$ tel que $A x_e = -b$, alors nous pouvons choisir $x_p(t) = x_e$. En effet, dans ce cas, $x_e$ est une solution particulière constante de l'équation $x'(t) = A x(t) + b$, car :
$$
A x_e + b = -b + b = 0
$$

Ainsi, $x_p(t) = x_e$ est une solution particulière constante, simplifiant encore le changement de variable et nous obtenons
$$
    x(t) = e^{tA} (x_0 - x_e) + x_e.
$$
:::